<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>


</head>



<body>
   
   
   
    <!-- Uses a transparent header that draws on top of the layout's background -->
<style>
    .demo-layout-transparent {
      background: url('Valorant.DE\ pic') center / cover; width: auto; height: 722px;
    }
    .demo-layout-transparent .mdl-layout__header,
    .demo-layout-transparent .mdl-layout__drawer-button {
      /* This background is dark, so we set text to white. Use 87% black instead if
         your background is light. */
      color: white;
    }
    </style>
    
    <div class="demo-layout-transparent mdl-layout mdl-js-layout">
      <header class="mdl-layout__header mdl-layout__header--transparent">
        <div class="mdl-layout__header-row">
          <!-- Title -->
          <span class="mdl-layout-title">Titel</span>
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <!-- Navigation -->
          <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="">Link</a>
            <a class="mdl-navigation__link" href="">Discord</a>
            <a class="mdl-navigation__link" href=""><!-- Rich Tooltip -->
                <div id="tt3" class="icon material-icons">cloud_upload</div>
                <div class="mdl-tooltip" data-mdl-for="tt3">
                Upload <strong>file.zip</strong>
                </div></a>
            <a class="mdl-navigation__link" href="">Link</a>
          </nav>
        </div>
      </header>
      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">Title</span>
        <nav class="mdl-navigation">
          <a class="mdl-navigation__link" href="">Rang/Statistiken</a>
          <a class="mdl-navigation__link" href="">Verlauf</a>
          <a class="mdl-navigation__link" href="">Agenten</a>
          <a class="mdl-navigation__link" href="">Spielverhalten</a>
        </nav>
      </div>
      <main class="mdl-layout__content">
      </main>
    </div>
</body>
</html>
